[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = [
    "ALL"
]
ignore = [
    "D100",    # Missing docst
    "D101",    # Missing class
    "D102",    # Missing docst
    "D103",    # Missing docst
    "D104",    # Missing docst
    "D105",    # Missing docst
    "D107",    # Missing docst
    "D212",    # Multi-line do
    "D400",    # First line sh
    "D415",    # First line sh
    "E701",    # Multiple stat
    "F401",    # `module` impo
    "I001",    # Import block 
    "N802",    # Function name
    "N803",    # Argument name
    "N806",    # Variable `var
    "N818",    # Exception nam
    "N999",    # Invalid modul
    "Q000",    # Single quotes
    "S101",    # Use of `asser
    "S311",    # Standard pseu
    "T201",    # `print` found
    "EM101",   # Exception mus
    "EM102",   # Exception mus
    "TC002",   # Move third-pa
    "TC003",   # Move standard
    "TD003",   # Missing issue
    "UP007",   # Use `X | Y` f
    "UP031",   # Use format sp
    "UP035",   # Import from `
    "UP037",   # Remove quotes
    "ANN401",  # Dynamically t
    "ARG001",  # Unused functi
    "ARG002",  # Unused method
    "ARG005",  # Unused lambda
    "COM812",  # Trailing comm
    "ERA001",  # Found comment
    "FBT001",  # Boolean-typed
    "FBT002",  # Boolean defau
    "ISC002",  # Implicitly co
    "PTH113",  # `os.path.isfi
    "PTH123",  # `open()` shou
    "PLR0913", # Too many argu
    "PLR1704", # Redefining ar
    "PLW0211", # First argumen
    "RUF001",  # Checks for am
    "RUF002",  # Checks for am
    "SLF001",  # Private membe
    "SIM108",  # Use ternary o
    "TRY003",  # Avoid specify
    "TRY300",  # Checks for re
]

[tool.pyright]
typeCheckingMode = "basic"
