name: CD

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  generate_json:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12" # 你想要使用的 Python 版本

      - name: Generate JSON
        run: python _workflow.py

      - name: Submit Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "[AUTO] Generate Directory JSON"
          add: '*'

      # 同步到又拍云
      - name: Deploy upyun
        run: |
          wget -O upx.tar.gz http://collection.b0.upaiyun.com/softwares/upx/upx_0.4.9_linux_amd64.tar.gz
          tar -zxf upx.tar.gz
          chmod +x upx
          ./upx login ${{ secrets.UP_BUCKET }} ${{ secrets.UP_OPERATOR }} ${{ secrets.UP_OPERATOR_PASSWORD }}
          ./upx sync ./ / --delete
          ./upx rm upx
          ./upx rm upx.tar.gz
          ./upx logout
